name: IRTH CICD Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version

    - name: Build with Maven
      run: mvn -B clean test -e

    - name: CICD-Test-Report
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: Automation Test Report
        path: src/test/Test Report/Test Execution Report.html

  EDGE-Browser:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: browser-actions/setup-edge@v1
        with:
          edge-version: beta
      - name: Print Edge version
        run: (Get-Item (Get-Command msedge).Source).VersionInfo.ProductVersion

      - name: Build with Maven
        run: mvn -B clean test -e

      - name: CICD-Test-Report
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: Automation Test Report
          path: src/test/Test Report/Test Execution Report.html